/*
account config
*/
export const ACCOUNT_CONFIG_CITY_NAME = 'ACCOUNT_CONFIG_CITY_NAME';



/*
auth
*/

// auth -- general
export const AUTH_DISPLAY = 'AUTH_DISPLAY';
export const AUTH_RESET = 'AUTH_RESET';
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
//export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
//export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

// auth -- users
export const AUTH_USER_REGISTER = 'AUTH_USER_REGISTER';
export const AUTH_USER_REGISTER_SUCCEEDED = 'AUTH_USER_REGISTER_SUCCEEDED';
export const AUTH_USER_REGISTER_FAILED = 'AUTH_USER_REGISTER_FAILED';

export const AUTH_USER_LOGIN = "AUTH_USER_LOGIN";
export const AUTH_USER_LOGIN_SUCCEEDED = "AUTH_USER_LOGIN_SUCCEEDED";
export const AUTH_USER_LOGIN_FAILED = "AUTH_USER_LOGIN_FAILED";

export const AUTH_USER_LOGOUT = "AUTH_USER_LOGOUT";
export const AUTH_USER_LOGOUT_SUCCEEDED = "AUTH_USER_LOGOUT_SUCCEEDED";
export const AUTH_USER_LOGOUT_FAILED = "AUTH_USER_LOGOUT_FAILED";

// auth -- managers
export const AUTH_MANAGER_REGISTER = 'AUTH_MANAGER_REGISTER';
export const AUTH_MANAGER_REGISTER_SUCCEEDED = 'AUTH_MANAGER_REGISTER_SUCCEEDED';
export const AUTH_MANAGER_REGISTER_FAILED = 'AUTH_MANAGER_REGISTER_FAILED';

export const AUTH_MANAGER_LOGIN = "AUTH_MANAGER_LOGIN";
export const AUTH_MANAGER_LOGIN_SUCCEEDED = "AUTH_MANAGER_LOGIN_SUCCEEDED";
export const AUTH_MANAGER_LOGIN_FAILED = "AUTH_MANAGER_LOGIN_FAILED";

export const AUTH_MANAGER_LOGOUT = "AUTH_MANAGER_LOGOUT";
export const AUTH_MANAGER_LOGOUT_SUCCEEDED = "AUTH_MANAGER_LOGOUT_SUCCEEDED";
export const AUTH_MANAGER_LOGOUT_FAILED = "AUTH_MANAGER_LOGOUT_FAILED";



/*
playgroundAndParkInspectionForm
*/

export const PLAYGROUND_AND_PARK_INSPECTION_FORM_HANDLE_INPUT_CHANGE = 'PLAYGROUND_AND_PARK_INSPECTION_FORM_HANDLE_INPUT_CHANGE';

export const PLAYGROUND_AND_PARK_INSPECTION_FORM_LOAD = 'PLAYGROUND_AND_PARK_INSPECTION_FORM_LOAD';
export const PLAYGROUND_AND_PARK_INSPECTION_FORM_LOAD_SUCCEEDED = 'PLAYGROUND_AND_PARK_INSPECTION_FORM_LOAD_SUCCEEDED';
export const PLAYGROUND_AND_PARK_INSPECTION_FORM_LOAD_FAILED = 'PLAYGROUND_AND_PARK_INSPECTION_FORM_LOAD_FAILED';

export const PLAYGROUND_AND_PARK_INSPECTION_FORM_SAVE = 'PLAYGROUND_AND_PARK_INSPECTION_FORM_SAVE';
export const PLAYGROUND_AND_PARK_INSPECTION_FORM_SAVE_SUCCEEDED = 'PLAYGROUND_AND_PARK_INSPECTION_FORM_SAVE_SUCCEEDED';
export const PLAYGROUND_AND_PARK_INSPECTION_FORM_SAVE_FAILED = 'PLAYGROUND_AND_PARK_INSPECTION_FORM_SAVE_FAILED';
